### ISSUE TITLE
Cmd Printer doesnt work in angular event it got the typings 

### ISSUE THREAD

**Issue by Vasanthvivi** [Dr-NULL/CMD-Printer#6]
The Cmd Printer is not working in Angular with common js configuration and the even the typings provided its not working what to do?

**Comment by Dr-NULL** [comment]
This package uses a SomatraPDF's executable file to manage the prints. For that, this library wasn't designed to be used in frontend applications. Instead, if you are developing a Frontend + Backend architecture:
- Install this package in your backend.
- Create an endpoint, and use the library there.
